### ISSUE TITLE
Issue Reading Checkpoints and Request for Sparse Encoder Code

### ISSUE THREAD

**Issue by makarovNick** [SimingYan/MaskFeat3D#1]
Hello,

First of all, thank you for your fantastic work and for providing the checkpoints in the Google Drive link! However, I am encountering an issue when trying to load the checkpoints using pytorch. When attempting to load scanobjectnn_finetune.pth using torch.load(), I receive the following error:
`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

It seems there may be a problem with the checkpoint files in the Google Drive link. Could you please check the checkpoints or provide guidance on how to load them properly?

Additionally, I read in your supplementary material, that you plan to add a Sparse Encoder. I'm very interested in this part of your work. Could you please provide the code or an estimated timeline for when it will be available?
Thanks!

**Comment by SimingYan** [comment]
Hi,

Thank you for reporting this issue! It seems the checkpoint files were accidentally corrupted during the upload. I will re-upload them soon. Since I am currently outside the U.S., the process may take a bit longer, but I will fix this as soon as possible.

Regarding the sparse encoder, we apologize that we currently don't have a clear timeline for its release. However, we based the sparse encoder model on the source code available here: https://github.com/chrischoy/SpatioTemporalSegmentation/blob/4afee296ebe387d9a06fc1b168c4af212a2b4804/models/res16unet.py#L330, and the model architecture is the same.

**Comment by SimingYan** [comment]
Hi, 

I have uploaded the updated checkpoints. Please let me know if there is any issue.
